### ISSUE TITLE
Question: Edit Button left from the value

### ISSUE THREAD

**Issue by esskar** [alioguzhan/react-editext#13]
Hi,

thanks for your library, it works really well.

Now, my question: Is it possible to put the edit button left from the value, and not right from the value?

**Comment by alioguzhan** [comment]
Hi, 
Yes it is possible I believe.  I can provide a prop like `actionsAlignment` with available values `["right", "left"]` which defaults to `right`.

With this approach, all action buttons will be located on the specified side of the `input` element. Is this what you are asking for, right?

**Comment by esskar** [comment]
Thanks for the quick answer, the first option would be enough.

but, what about something like this

```actionsAlignment = { 'edit': 'left', 'save': 'right', 'cancel': 'left' }```

and setting

```actionsAlignment = 'left'```

would be the same as 

```actionsAlignment = { 'edit': 'left', 'save': 'left', 'cancel': 'left' }```

and 

```actionsAlignment = { 'edit': 'left' }```

would be the same as 

```actionsAlignment = { 'edit': 'left', 'save': 'right', 'cancel': 'right' }```

so, the default is 'right' but setting each button individual is possible as well

**Comment by alioguzhan** [comment]
Thanks. I will consider these and will release a new version in a day or two. 

Btw, we still can make these arrangements with some ugly CSS by using `float`s :)

**Comment by alioguzhan** [comment]
Hey @esskar ,

I just released a new version with `buttonsAlign` prop support. It is not so much advanced but it should provide basic alignment between `input` and `buttons`.  Please see [the new section on the example page](https://alioguzhan.github.io/react-editext/#change-buttons-location).

PS: I decided to set options as `before` and `after`. Since users can locate buttons container not only horizontally but also vertically; it made more sense to me to design them in `before` or `after` the input context. Feel free to discuss with me.

**Comment by esskar** [comment]
thats kinda nice, thanks.

**Comment by alioguzhan** [comment]
@all-contributors please add @esskar  for his questions and ideas.
