### ISSUE TITLE
console.error() when pass a react element

### ISSUE THREAD

**Issue by BrunoAderaldo** [alioguzhan/react-editext#4]
**Hello, this component saved me a good time yesterday. Thank you!**

I know that in read.md it says that the following properties only accept string.
![image](https://user-images.githubusercontent.com/14007590/53489091-f9024580-3a6e-11e9-8002-12e4b05d58f4.png)

That is why this issue is not an error. But I really wanted to mass an icon (svg - react - feather). I can do this, everything works fine but it gets a bug in the console.

Error:
![image](https://user-images.githubusercontent.com/14007590/53488890-52b64000-3a6e-11e9-833f-073960544125.png)

**Thanks again, this component is very useful.**

**Comment by alioguzhan** [comment]
Hey, you are right. I should change the propType config for these props. I will fix it and send a new release in a few days. I will update here!

**Comment by BrunoAderaldo** [comment]
Oh nice, i appreciate it! :clap:

**Comment by alioguzhan** [comment]
I fixed the issue. Changed the propNames like `editButtonContent`, `saveButtonContent` and `cancelButtonContent` instead of `xxxButtonText`. You will need to change a few things in your code. 

I will also implement a few nice features to make it more customizable for developers. So the next version will probably `3.x.x`. 

It probably will be here in next 24 hours !

**Comment by alioguzhan** [comment]
Hey! 

I just release a new version to NPM 📦 . Please see the [CHANGELOG](https://github.com/alioguzhan/react-editext/blob/master/CHANGELOG.md#300-2019-02-27)

Also, check new and updated example from [Examples Page](https://alioguzhan.github.io/react-editext/)

**Comment by alioguzhan** [comment]
@all-contributors please add @BrunoAderaldo for bug and code
