### ISSUE TITLE
How can i trigger cancel or save event?

### ISSUE THREAD

**Issue by meseven** [alioguzhan/react-editext#49]
Hi,
How can i trigger cancel or save event from outside that component?

**Comment by alioguzhan** [comment]
Hey, 

I didn't make that part of this component `controlled`. Since this is an input component, I thought there will be always a user interaction to trigger `cancel` or `save` events.

If you can think of any use case for this we can talk about it. 

Right now the only controlled feature is toggling edit mode with `editing` prop.
